### PR TITLE
Adding the hero graphics for different directions.

### PR DESCRIPTION
**Pull request by ehgoodenough**
## Summary ##

I wanted to begin copying some of the assets from Nothingness into the game, and I started by reintegrating the hero with his graphics. It is far from perfect; some of the image is clipped off a bit, and it still isn't animated, but at least it has directional rendering.

## Link ##

http://mocsarcade.github.io/renothingness/pull/5

## Github Selfie ##

selfie-0

### CODE REVIEW

**Comment by ehgoodenough** [comment]
I fixed the merge conflicts!

**Comment by CodenameStranger** [comment]
You guys are some coding fools

**Comment by ehgoodenough** [comment]
@CodenameStranger: Yeah! We're building lots of cool stuff. I'm trying to get Joey acquanited with javascript by having him recreate the game we made last semester in javascript. Later on, want to have a js weekend as well?

**Comment by CodenameStranger** [comment]
Of course! I will be brushing up. Hopefully I will have a good android game
to show off ;)

**Comment by ehgoodenough** [comment]
Niiiiice! Make it happen!

**Comment by ehgoodenough** [comment]
@jshiraef: do a code review, bro!

**Pull request merged**
